// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9HJhN7jm9_rDTV_yfTFjspKsbJ3mlo_g',
    appId: '1:1019000214736:web:c0fbf9d54dbd98fca6fad5',
    messagingSenderId: '1019000214736',
    projectId: 'benchmark-301314',
    authDomain: 'benchmark-301314.firebaseapp.com',
    storageBucket: 'benchmark-301314.appspot.com',
    measurementId: 'G-6D7WNFRNBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQTj8YCNGdaEb4cpTrooZbcdZKFJf77Xg',
    appId: '1:1019000214736:android:572e29342b4f0d66a6fad5',
    messagingSenderId: '1019000214736',
    projectId: 'benchmark-301314',
    storageBucket: 'benchmark-301314.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBbVFdC9pf_Tu0p2eLQwyo3dGtvL1thCA',
    appId: '1:1019000214736:ios:e6b3e813f31f9d5da6fad5',
    messagingSenderId: '1019000214736',
    projectId: 'benchmark-301314',
    storageBucket: 'benchmark-301314.appspot.com',
    androidClientId: '1019000214736-63ehvh3q4qtpbgse54c3k3n816o8v5m9.apps.googleusercontent.com',
    iosClientId: '1019000214736-erj85mnc6sb2ml2iggbotddet4mt2s5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolDiarySept13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBbVFdC9pf_Tu0p2eLQwyo3dGtvL1thCA',
    appId: '1:1019000214736:ios:e6b3e813f31f9d5da6fad5',
    messagingSenderId: '1019000214736',
    projectId: 'benchmark-301314',
    storageBucket: 'benchmark-301314.appspot.com',
    androidClientId: '1019000214736-63ehvh3q4qtpbgse54c3k3n816o8v5m9.apps.googleusercontent.com',
    iosClientId: '1019000214736-erj85mnc6sb2ml2iggbotddet4mt2s5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolDiarySept13',
  );
}
